### ISSUE TITLE
How to force remove scrap guard

### ISSUE THREAD

**Issue by ghostdevv** [TechnologicNick/Scrap-Guard#1]
I accidently locked myself out of a creation that isn't on a lift and I need to unlock it. I thought I might be able to temporarily disable the mod and then add it back once I deleted the block but that doesn't work. I opened the world file in sqlite but can't figure out what needs to be deleted/changed for scrap guard to let me interact to remove or edit the settings

**Comment by TechnologicNick** [comment]
We've spoken on Discord, but I'll just leave this here for others who might stumble upon it.

Currently there's currently no built-in way to do this. You can add `self.shape:destroyShape(); return;` below [this line](https://github.com/TechnologicNick/Scrap-Guard/blob/master/Scripts/ScrapGuard.lua#L261) and reload the world to remove all loaded Scrap Guard part instances. You can then place a new Scrap Guard part on world/game mode and allow modifications.

I might look into a proper way of doing this in the future, but no promises.
